# Dependencies
markdown:         kramdown
highlighter:      rouge
plugins:          [jekyll-paginate]

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Gender and Sexuality in the Ancient World
tagline:          'Gender and Sexuality in the Ancient World'
course_number:    'CLAS 199 01'
semester:         'Spring 2019'
location:         'College of the Holy Cross'
url:              http://dlibatique.github.io/CLAS199
baseurl:          /

author:
  name:           'Daniel Libatique'
  url:            https://dlibatique.github.io

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/dlibatique/CLAS199

pages:
    - resources
    - nuts
    - grading
    - schedule
